source "https://rubygems.org"

gem "activesupport"

group :development do
  gem "rake"
  gem "standardrb"
  gem "whats_up"
end

group :test do
  gem "minitest"
  gem "minitest-reporters"
  gem "rspec"
  gem "test-unit"
end
