#!/bin/bash

trap "echo Exited!; exit;" SIGINT SIGTERM

while true; do
  ag -g '\.rb$' | entr -c -d -p -s 'bundle exec rubocop -A gilded_rose.rb; bundle exec reek gilded_rose.rb; bundle exec ruby *_test.rb'
done
